var namespaces_dup =
[
    [ "custom_tool_button", "namespacecustom__tool__button.html", "namespacecustom__tool__button" ],
    [ "dialog_about_ui", "namespacedialog__about__ui.html", "namespacedialog__about__ui" ],
    [ "dialog_banking_ui", "namespacedialog__banking__ui.html", "namespacedialog__banking__ui" ],
    [ "dialog_commit_ui", "namespacedialog__commit__ui.html", "namespacedialog__commit__ui" ],
    [ "dialog_company_ui", "namespacedialog__company__ui.html", "namespacedialog__company__ui" ],
    [ "dialog_contact_ui", "namespacedialog__contact__ui.html", "namespacedialog__contact__ui" ],
    [ "dialog_document_ui", "namespacedialog__document__ui.html", "namespacedialog__document__ui" ],
    [ "dialog_help_ui", "namespacedialog__help__ui.html", "namespacedialog__help__ui" ],
    [ "dialog_invoice_general_ui", "namespacedialog__invoice__general__ui.html", "namespacedialog__invoice__general__ui" ],
    [ "dialog_receipt_ui", "namespacedialog__receipt__ui.html", "namespacedialog__receipt__ui" ],
    [ "dialog_splash_ui", "namespacedialog__splash__ui.html", "namespacedialog__splash__ui" ],
    [ "DoxygenCreator", "namespace_doxygen_creator.html", "namespace_doxygen_creator" ],
    [ "Executable", "namespace_executable.html", "namespace_executable" ],
    [ "invoice_data_ui", "namespaceinvoice__data__ui.html", "namespaceinvoice__data__ui" ],
    [ "invoice_discounts_data_ui", "namespaceinvoice__discounts__data__ui.html", "namespaceinvoice__discounts__data__ui" ],
    [ "invoice_item_data_ui", "namespaceinvoice__item__data__ui.html", "namespaceinvoice__item__data__ui" ],
    [ "invoice_item_discounts_data_ui", "namespaceinvoice__item__discounts__data__ui.html", "namespaceinvoice__item__discounts__data__ui" ],
    [ "invoice_item_surcharges_data_ui", "namespaceinvoice__item__surcharges__data__ui.html", "namespaceinvoice__item__surcharges__data__ui" ],
    [ "invoice_surcharges_data_ui", "namespaceinvoice__surcharges__data__ui.html", "namespaceinvoice__surcharges__data__ui" ],
    [ "invoice_tax_data_ui", "namespaceinvoice__tax__data__ui.html", "namespaceinvoice__tax__data__ui" ],
    [ "mainwindow_ui", "namespacemainwindow__ui.html", "namespacemainwindow__ui" ],
    [ "Source", "namespace_source.html", "namespace_source" ],
    [ "tab_dashboard_ui", "namespacetab__dashboard__ui.html", "namespacetab__dashboard__ui" ],
    [ "tab_export_ui", "namespacetab__export__ui.html", "namespacetab__export__ui" ],
    [ "tab_settings_ui", "namespacetab__settings__ui.html", "namespacetab__settings__ui" ],
    [ "tab_table_filter_ui", "namespacetab__table__filter__ui.html", "namespacetab__table__filter__ui" ],
    [ "update_py_requirements", "namespaceupdate__py__requirements.html", "namespaceupdate__py__requirements" ]
];