# Form implementation generated from reading ui file 'tabs/tab_settings.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(991, 584)
        self.gridLayout_3 = QtWidgets.QGridLayout(Settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(parent=Settings)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_title = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 1)
        self.company_logo = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.company_logo.sizePolicy().hasHeightForWidth())
        self.company_logo.setSizePolicy(sizePolicy)
        self.company_logo.setText("")
        self.company_logo.setObjectName("company_logo")
        self.gridLayout.addWidget(self.company_logo, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=Settings)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.company_data = QtWidgets.QTextEdit(parent=self.widget_2)
        self.company_data.setObjectName("company_data")
        self.gridLayout_2.addWidget(self.company_data, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 2, 0, 1, 1)
        self.btn_change_company_data = QtWidgets.QPushButton(parent=Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_change_company_data.sizePolicy().hasHeightForWidth())
        self.btn_change_company_data.setSizePolicy(sizePolicy)
        self.btn_change_company_data.setObjectName("btn_change_company_data")
        self.gridLayout_3.addWidget(self.btn_change_company_data, 1, 0, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.lbl_title.setText(_translate("Settings", "Titel"))
        self.btn_change_company_data.setText(_translate("Settings", "Persönliche Daten ändern"))
