# Form implementation generated from reading ui file 'dialogs/dialog_about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(429, 266)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AboutDialog)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imagePlaceholder = QtWidgets.QLabel(parent=AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagePlaceholder.sizePolicy().hasHeightForWidth())
        self.imagePlaceholder.setSizePolicy(sizePolicy)
        self.imagePlaceholder.setMaximumSize(QtCore.QSize(150, 150))
        self.imagePlaceholder.setText("")
        self.imagePlaceholder.setPixmap(QtGui.QPixmap("dialogs\\../../Resources/app.ico"))
        self.imagePlaceholder.setScaledContents(True)
        self.imagePlaceholder.setObjectName("imagePlaceholder")
        self.verticalLayout_2.addWidget(self.imagePlaceholder)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_productName = QtWidgets.QLabel(parent=AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_productName.sizePolicy().hasHeightForWidth())
        self.lbl_productName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lbl_productName.setFont(font)
        self.lbl_productName.setObjectName("lbl_productName")
        self.verticalLayout.addWidget(self.lbl_productName)
        self.lbl_productDescription = QtWidgets.QLabel(parent=AboutDialog)
        self.lbl_productDescription.setObjectName("lbl_productDescription")
        self.verticalLayout.addWidget(self.lbl_productDescription)
        self.lbl_version = QtWidgets.QLabel(parent=AboutDialog)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        self.lbl_copyright = QtWidgets.QLabel(parent=AboutDialog)
        self.lbl_copyright.setObjectName("lbl_copyright")
        self.verticalLayout.addWidget(self.lbl_copyright)
        self.lbl_license = QtWidgets.QLabel(parent=AboutDialog)
        self.lbl_license.setObjectName("lbl_license")
        self.verticalLayout.addWidget(self.lbl_license)
        self.lbl_home = QtWidgets.QLabel(parent=AboutDialog)
        self.lbl_home.setObjectName("lbl_home")
        self.verticalLayout.addWidget(self.lbl_home)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.lbl_productName.setText(_translate("AboutDialog", "ElsterBooks"))
        self.lbl_productDescription.setText(_translate("AboutDialog", "Buchhaltung"))
        self.lbl_version.setText(_translate("AboutDialog", "Version:"))
        self.lbl_copyright.setText(_translate("AboutDialog", "Copyright"))
        self.lbl_license.setText(_translate("AboutDialog", "License"))
        self.lbl_home.setText(_translate("AboutDialog", "Home:"))
