# Form implementation generated from reading ui file 'dialogs/dialog_commit.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommitDialog(object):
    def setupUi(self, CommitDialog):
        CommitDialog.setObjectName("CommitDialog")
        CommitDialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CommitDialog.sizePolicy().hasHeightForWidth())
        CommitDialog.setSizePolicy(sizePolicy)
        CommitDialog.setMinimumSize(QtCore.QSize(300, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(CommitDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=CommitDialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=CommitDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pte_changes = QtWidgets.QPlainTextEdit(parent=CommitDialog)
        self.pte_changes.setObjectName("pte_changes")
        self.verticalLayout.addWidget(self.pte_changes)
        self.line = QtWidgets.QFrame(parent=CommitDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(parent=CommitDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pte_commit_text = QtWidgets.QPlainTextEdit(parent=CommitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pte_commit_text.sizePolicy().hasHeightForWidth())
        self.pte_commit_text.setSizePolicy(sizePolicy)
        self.pte_commit_text.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pte_commit_text.setObjectName("pte_commit_text")
        self.verticalLayout.addWidget(self.pte_commit_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_diff = QtWidgets.QPushButton(parent=CommitDialog)
        self.btn_diff.setObjectName("btn_diff")
        self.horizontalLayout.addWidget(self.btn_diff)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_no = QtWidgets.QPushButton(parent=CommitDialog)
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout.addWidget(self.btn_no)
        self.btn_yes = QtWidgets.QPushButton(parent=CommitDialog)
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout.addWidget(self.btn_yes)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CommitDialog)
        QtCore.QMetaObject.connectSlotsByName(CommitDialog)

    def retranslateUi(self, CommitDialog):
        _translate = QtCore.QCoreApplication.translate
        CommitDialog.setWindowTitle(_translate("CommitDialog", "About"))
        self.label.setText(_translate("CommitDialog", "Möchten Sie Ihre Änderungen committen?"))
        self.label_3.setText(_translate("CommitDialog", "Änderungen:"))
        self.label_2.setText(_translate("CommitDialog", "Commit Text"))
        self.pte_commit_text.setPlaceholderText(_translate("CommitDialog", "Commit Text eingeben"))
        self.btn_diff.setText(_translate("CommitDialog", "Änderungen anzeigen"))
        self.btn_no.setText(_translate("CommitDialog", "Nein"))
        self.btn_yes.setText(_translate("CommitDialog", "Ja (Commit)"))
