# Form implementation generated from reading ui file 'dialogs/dialog_document.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogDocument(object):
    def setupUi(self, DialogDocument):
        DialogDocument.setObjectName("DialogDocument")
        DialogDocument.resize(490, 409)
        DialogDocument.setMinimumSize(QtCore.QSize(400, 210))
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogDocument)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=DialogDocument)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.de_document_date = QtWidgets.QDateEdit(parent=self.groupBox)
        self.de_document_date.setObjectName("de_document_date")
        self.gridLayout.addWidget(self.de_document_date, 5, 0, 1, 1)
        self.lbl_document_date = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_document_date.setObjectName("lbl_document_date")
        self.gridLayout.addWidget(self.lbl_document_date, 0, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 5, 1, 1, 1)
        self.lbl_description = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_description.setObjectName("lbl_description")
        self.gridLayout.addWidget(self.lbl_description, 7, 0, 1, 1)
        self.pte_description = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.pte_description.setObjectName("pte_description")
        self.gridLayout.addWidget(self.pte_description, 8, 0, 1, 2)
        self.btn_delete = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 6, 1, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 7, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(DialogDocument)
        QtCore.QMetaObject.connectSlotsByName(DialogDocument)
        DialogDocument.setTabOrder(self.de_document_date, self.btn_save)
        DialogDocument.setTabOrder(self.btn_save, self.btn_delete)
        DialogDocument.setTabOrder(self.btn_delete, self.btn_cancel)

    def retranslateUi(self, DialogDocument):
        _translate = QtCore.QCoreApplication.translate
        DialogDocument.setWindowTitle(_translate("DialogDocument", "Form"))
        self.groupBox.setTitle(_translate("DialogDocument", "Dokument"))
        self.lbl_document_date.setText(_translate("DialogDocument", "Datum"))
        self.btn_save.setText(_translate("DialogDocument", "Speichern"))
        self.lbl_description.setText(_translate("DialogDocument", "Beschreibung"))
        self.btn_delete.setText(_translate("DialogDocument", "Löschen"))
        self.btn_cancel.setText(_translate("DialogDocument", "Abbrechen"))
