# Form implementation generated from reading ui file 'dialogs/dialog_splash.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(800, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SplashScreen.sizePolicy().hasHeightForWidth())
        SplashScreen.setSizePolicy(sizePolicy)
        self.lbl_productName = QtWidgets.QLabel(parent=SplashScreen)
        self.lbl_productName.setGeometry(QtCore.QRect(580, 70, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_productName.sizePolicy().hasHeightForWidth())
        self.lbl_productName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.lbl_productName.setFont(font)
        self.lbl_productName.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lbl_productName.setObjectName("lbl_productName")
        self.lbl_version = QtWidgets.QLabel(parent=SplashScreen)
        self.lbl_version.setGeometry(QtCore.QRect(570, 120, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_version.sizePolicy().hasHeightForWidth())
        self.lbl_version.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_version.setFont(font)
        self.lbl_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lbl_version.setIndent(11)
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_icon_placeholder = QtWidgets.QLabel(parent=SplashScreen)
        self.lbl_icon_placeholder.setGeometry(QtCore.QRect(0, 0, 800, 514))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_icon_placeholder.sizePolicy().hasHeightForWidth())
        self.lbl_icon_placeholder.setSizePolicy(sizePolicy)
        self.lbl_icon_placeholder.setMaximumSize(QtCore.QSize(1250, 804))
        self.lbl_icon_placeholder.setScaledContents(True)
        self.lbl_icon_placeholder.setObjectName("lbl_icon_placeholder")
        self.lbl_prerelease = QtWidgets.QLabel(parent=SplashScreen)
        self.lbl_prerelease.setGeometry(QtCore.QRect(580, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_prerelease.setFont(font)
        self.lbl_prerelease.setObjectName("lbl_prerelease")
        self.lbl_build_name = QtWidgets.QLabel(parent=SplashScreen)
        self.lbl_build_name.setGeometry(QtCore.QRect(20, 480, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_build_name.setFont(font)
        self.lbl_build_name.setObjectName("lbl_build_name")
        self.lbl_icon_placeholder.raise_()
        self.lbl_productName.raise_()
        self.lbl_version.raise_()
        self.lbl_prerelease.raise_()
        self.lbl_build_name.raise_()

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "ElsterBooks"))
        self.lbl_productName.setText(_translate("SplashScreen", "ElsterBooks"))
        self.lbl_version.setText(_translate("SplashScreen", "1.0.0.0"))
        self.lbl_icon_placeholder.setText(_translate("SplashScreen", "icon_placeholder"))
        self.lbl_prerelease.setText(_translate("SplashScreen", "Prerelease Build"))
        self.lbl_build_name.setText(_translate("SplashScreen", "Build Name"))
