# Form implementation generated from reading ui file 'dialogs/dialog_help.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        HelpDialog.resize(700, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HelpDialog.sizePolicy().hasHeightForWidth())
        HelpDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_helpMenu = QtWidgets.QTabWidget(parent=HelpDialog)
        self.tabWidget_helpMenu.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget_helpMenu.setObjectName("tabWidget_helpMenu")
        self.tabHelpGeneral = QtWidgets.QWidget()
        self.tabHelpGeneral.setObjectName("tabHelpGeneral")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabHelpGeneral)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.helpTextGeneral = QtWidgets.QTextBrowser(parent=self.tabHelpGeneral)
        self.helpTextGeneral.setOpenExternalLinks(True)
        self.helpTextGeneral.setObjectName("helpTextGeneral")
        self.verticalLayout_7.addWidget(self.helpTextGeneral)
        self.tabWidget_helpMenu.addTab(self.tabHelpGeneral, "")
        self.tabHelpInvoice = QtWidgets.QWidget()
        self.tabHelpInvoice.setObjectName("tabHelpInvoice")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabHelpInvoice)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.helpTextInvoice = QtWidgets.QTextBrowser(parent=self.tabHelpInvoice)
        self.helpTextInvoice.setOpenExternalLinks(True)
        self.helpTextInvoice.setObjectName("helpTextInvoice")
        self.verticalLayout_8.addWidget(self.helpTextInvoice)
        self.tabWidget_helpMenu.addTab(self.tabHelpInvoice, "")
        self.tabHelpBooking = QtWidgets.QWidget()
        self.tabHelpBooking.setObjectName("tabHelpBooking")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabHelpBooking)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.helpTextBooking = QtWidgets.QTextBrowser(parent=self.tabHelpBooking)
        self.helpTextBooking.setOpenExternalLinks(True)
        self.helpTextBooking.setObjectName("helpTextBooking")
        self.verticalLayout_3.addWidget(self.helpTextBooking)
        self.tabWidget_helpMenu.addTab(self.tabHelpBooking, "")
        self.tabHelpExport = QtWidgets.QWidget()
        self.tabHelpExport.setObjectName("tabHelpExport")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabHelpExport)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.helpTextExport = QtWidgets.QTextBrowser(parent=self.tabHelpExport)
        self.helpTextExport.setOpenExternalLinks(True)
        self.helpTextExport.setObjectName("helpTextExport")
        self.verticalLayout_9.addWidget(self.helpTextExport)
        self.tabWidget_helpMenu.addTab(self.tabHelpExport, "")
        self.tabHelpSettings = QtWidgets.QWidget()
        self.tabHelpSettings.setObjectName("tabHelpSettings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabHelpSettings)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.helpTextSettings = QtWidgets.QTextBrowser(parent=self.tabHelpSettings)
        self.helpTextSettings.setOpenExternalLinks(True)
        self.helpTextSettings.setObjectName("helpTextSettings")
        self.verticalLayout_4.addWidget(self.helpTextSettings)
        self.tabWidget_helpMenu.addTab(self.tabHelpSettings, "")
        self.verticalLayout.addWidget(self.tabWidget_helpMenu)

        self.retranslateUi(HelpDialog)
        self.tabWidget_helpMenu.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "Help"))
        self.helpTextGeneral.setHtml(_translate("HelpDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_helpMenu.setTabText(self.tabWidget_helpMenu.indexOf(self.tabHelpGeneral), _translate("HelpDialog", "Allgemein"))
        self.helpTextInvoice.setHtml(_translate("HelpDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_helpMenu.setTabText(self.tabWidget_helpMenu.indexOf(self.tabHelpInvoice), _translate("HelpDialog", "Rechnungen"))
        self.helpTextBooking.setHtml(_translate("HelpDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_helpMenu.setTabText(self.tabWidget_helpMenu.indexOf(self.tabHelpBooking), _translate("HelpDialog", "Buchhaltung"))
        self.helpTextExport.setHtml(_translate("HelpDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_helpMenu.setTabText(self.tabWidget_helpMenu.indexOf(self.tabHelpExport), _translate("HelpDialog", "Export"))
        self.helpTextSettings.setHtml(_translate("HelpDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_helpMenu.setTabText(self.tabWidget_helpMenu.indexOf(self.tabHelpSettings), _translate("HelpDialog", "Einstellungen"))
