# Form implementation generated from reading ui file 'dialogs/dialog_invoice_general.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogInvoice(object):
    def setupUi(self, DialogInvoice):
        DialogInvoice.setObjectName("DialogInvoice")
        DialogInvoice.resize(920, 785)
        DialogInvoice.setMinimumSize(QtCore.QSize(400, 210))
        self.gridLayout_3 = QtWidgets.QGridLayout(DialogInvoice)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=DialogInvoice)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.cb_extended = QtWidgets.QCheckBox(parent=DialogInvoice)
        self.cb_extended.setObjectName("cb_extended")
        self.gridLayout_3.addWidget(self.cb_extended, 3, 5, 1, 1)
        self.btn_create = CustomToolButton(parent=DialogInvoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create.sizePolicy().hasHeightForWidth())
        self.btn_create.setSizePolicy(sizePolicy)
        self.btn_create.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_create.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_create.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.btn_create.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.btn_create.setObjectName("btn_create")
        self.gridLayout_3.addWidget(self.btn_create, 3, 7, 1, 1)
        self.cb_contact_template = QtWidgets.QComboBox(parent=DialogInvoice)
        self.cb_contact_template.setMinimumSize(QtCore.QSize(400, 0))
        self.cb_contact_template.setObjectName("cb_contact_template")
        self.gridLayout_3.addWidget(self.cb_contact_template, 3, 0, 1, 1)
        self.scroll_area = QtWidgets.QScrollArea(parent=DialogInvoice)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 906, 729))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scroll_area, 4, 0, 1, 8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 2, 1, 1)
        self.btn_export = QtWidgets.QPushButton(parent=DialogInvoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_export.setObjectName("btn_export")
        self.gridLayout_3.addWidget(self.btn_export, 3, 4, 1, 1)
        self.btn_import = QtWidgets.QPushButton(parent=DialogInvoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        self.btn_import.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_3.addWidget(self.btn_import, 3, 3, 1, 1)

        self.retranslateUi(DialogInvoice)
        QtCore.QMetaObject.connectSlotsByName(DialogInvoice)

    def retranslateUi(self, DialogInvoice):
        _translate = QtCore.QCoreApplication.translate
        DialogInvoice.setWindowTitle(_translate("DialogInvoice", "Form"))
        self.label.setText(_translate("DialogInvoice", "Kontaktvorlage"))
        self.cb_extended.setText(_translate("DialogInvoice", "Erweiterter Modus"))
        self.btn_create.setText(_translate("DialogInvoice", "Erstellen"))
        self.btn_export.setText(_translate("DialogInvoice", "Export"))
        self.btn_import.setText(_translate("DialogInvoice", "Import"))
from Source.Views.widgets.custom_tool_button import CustomToolButton
