# Form implementation generated from reading ui file 'widgets/invoice_item_surcharges_data.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InvoiceItemSurchargeData(object):
    def setupUi(self, InvoiceItemSurchargeData):
        InvoiceItemSurchargeData.setObjectName("InvoiceItemSurchargeData")
        InvoiceItemSurchargeData.resize(549, 99)
        self.gridLayout_3 = QtWidgets.QGridLayout(InvoiceItemSurchargeData)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=InvoiceItemSurchargeData)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_percent_symbol = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_percent_symbol.sizePolicy().hasHeightForWidth())
        self.lbl_percent_symbol.setSizePolicy(sizePolicy)
        self.lbl_percent_symbol.setObjectName("lbl_percent_symbol")
        self.gridLayout_4.addWidget(self.lbl_percent_symbol, 1, 1, 1, 1)
        self.lbl_percent = QtWidgets.QLabel(parent=self.frame)
        self.lbl_percent.setObjectName("lbl_percent")
        self.gridLayout_4.addWidget(self.lbl_percent, 0, 0, 1, 1)
        self.lbl_net_amount_symbol = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_net_amount_symbol.sizePolicy().hasHeightForWidth())
        self.lbl_net_amount_symbol.setSizePolicy(sizePolicy)
        self.lbl_net_amount_symbol.setObjectName("lbl_net_amount_symbol")
        self.gridLayout_4.addWidget(self.lbl_net_amount_symbol, 1, 3, 1, 1)
        self.lbl_net_amount = QtWidgets.QLabel(parent=self.frame)
        self.lbl_net_amount.setObjectName("lbl_net_amount")
        self.gridLayout_4.addWidget(self.lbl_net_amount, 0, 2, 1, 1)
        self.dsb_net_amount = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.dsb_net_amount.setMaximum(999999999.99)
        self.dsb_net_amount.setObjectName("dsb_net_amount")
        self.gridLayout_4.addWidget(self.dsb_net_amount, 1, 2, 1, 1)
        self.dsb_percent = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.dsb_percent.setMaximum(100.0)
        self.dsb_percent.setObjectName("dsb_percent")
        self.gridLayout_4.addWidget(self.dsb_percent, 1, 0, 1, 1)
        self.lbl_reason = QtWidgets.QLabel(parent=self.frame)
        self.lbl_reason.setObjectName("lbl_reason")
        self.gridLayout_4.addWidget(self.lbl_reason, 0, 4, 1, 1)
        self.le_reason = QtWidgets.QLineEdit(parent=self.frame)
        self.le_reason.setObjectName("le_reason")
        self.gridLayout_4.addWidget(self.le_reason, 1, 4, 1, 1)
        self.lbl_reason_code = QtWidgets.QLabel(parent=self.frame)
        self.lbl_reason_code.setObjectName("lbl_reason_code")
        self.gridLayout_4.addWidget(self.lbl_reason_code, 0, 5, 1, 1)
        self.cb_reason_code = QtWidgets.QComboBox(parent=self.frame)
        self.cb_reason_code.setObjectName("cb_reason_code")
        self.gridLayout_4.addWidget(self.cb_reason_code, 1, 5, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(InvoiceItemSurchargeData)
        QtCore.QMetaObject.connectSlotsByName(InvoiceItemSurchargeData)

    def retranslateUi(self, InvoiceItemSurchargeData):
        _translate = QtCore.QCoreApplication.translate
        InvoiceItemSurchargeData.setWindowTitle(_translate("InvoiceItemSurchargeData", "Form"))
        self.lbl_percent_symbol.setText(_translate("InvoiceItemSurchargeData", "%"))
        self.lbl_percent.setText(_translate("InvoiceItemSurchargeData", "<html><head/><body><p>Zuschlag <span style=\" font-size:7pt; color:#808080;\">(BT-143)</span></p></body></html>"))
        self.lbl_net_amount_symbol.setText(_translate("InvoiceItemSurchargeData", "€"))
        self.lbl_net_amount.setText(_translate("InvoiceItemSurchargeData", "<html><head/><body><p>Betrag (Netto) <span style=\" font-size:7pt; color:#808080;\">(BT-141)</span></p></body></html>"))
        self.lbl_reason.setText(_translate("InvoiceItemSurchargeData", "<html><head/><body><p>Grund <span style=\" font-size:7pt; color:#808080;\">(BT-144)</span></p></body></html>"))
        self.le_reason.setPlaceholderText(_translate("InvoiceItemSurchargeData", "Grund"))
        self.lbl_reason_code.setText(_translate("InvoiceItemSurchargeData", "<html><head/><body><p>Code des Grundes <span style=\" font-size:7pt; color:#808080;\">(BT-145)</span></p></body></html>"))
